import { TokenData } from "../../types";

export const APES: TokenData[] = [
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Red",
      head: "Nothing",
      eyes: "VR",
      ears: "Nothing",
      mouth: "Nothing",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Albino",
      head: "Military Hat",
      eyes: "Stoned",
      ears: "Nothing",
      mouth: "Smile",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Mutant",
      head: "Nothing",
      eyes: "Angry Visor",
      ears: "Nothing",
      mouth: "Nothing",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Brown",
      head: "Crown",
      eyes: "Rainbow Visor",
      ears: "Nothing",
      mouth: "Blunt",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Robot",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Red NT Mask",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Zombie",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Cigar",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Black",
      head: "Saka",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Banana",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Red",
      head: "Nothing",
      eyes: "VR",
      ears: "Nothing",
      mouth: "Nothing",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Albino",
      head: "Military Hat",
      eyes: "Stoned",
      ears: "Nothing",
      mouth: "Smile",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Mutant",
      head: "Nothing",
      eyes: "Angry Visor",
      ears: "Nothing",
      mouth: "Nothing",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Brown",
      head: "Crown",
      eyes: "Rainbow Visor",
      ears: "Nothing",
      mouth: "Blunt",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Robot",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Red NT Mask",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Zombie",
      head: "Nothing",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Cigar",
      background: "Binary",
    },
  },
  {
    index: "1231",
    token: "123123",
    rank: "120",
    traits: {
      ape: "Black",
      head: "Saka",
      eyes: "Nothing",
      ears: "Nothing",
      mouth: "Banana",
      background: "Binary",
    },
  },
];

export default APES;
